name: food_pick_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  flutter_naver_map: ^1.1.2
  geolocator: ^11.0.0
  http: ^1.2.0
  daum_postcode_search: ^0.0.2
  flutter_inappwebview: ^5.8.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true


